name: ci kubernetes microservicio

on:
  push:
    branches: ["main"]
    paths: 
      - "labs/Laboratorio10/**"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: labs/Laboratorio10
    steps:
      - name: revisar
        uses: actions/checkout@v4

      - name: build
        run: docker build -t ejemplo-ms:${{  github.sha }} .
     
